### ISSUE TITLE
e2e testing suite for examples

### ISSUE THREAD

**Issue by danielroe** [nuxt/examples#2]

**Comment by Lehoczky** [comment]
Hi Guys 👋🏿 

Is this this task up for grabs? Would you prefer a specific e2e framework? I'd gladly implement as many scenarios with [playwright](https://playwright.dev/) as I can.

**Comment by danielroe** [comment]
That sounds fantastic and I really appreciate it! ❤️ Playwright would indeed be great. I'd like to be able to run them wholly within an action so we can run them in nuxt/ecosystem-ci.
