### ISSUE TITLE
Documentation: ErrorHandling - Stackblitz example of handling different kind of errors not working. It shows a blank page

### ISSUE THREAD

**Issue by awacode21** [nuxt/examples#61]
### Environment

https://nuxt.com/docs/examples/advanced/error-handling

### Reproduction

See your own here: https://nuxt.com/docs/examples/advanced/error-handling

### Describe the bug

Stackblitz example of handling different kind of errors is not working. It tries starting/initializing, and then shows a blank page

### Additional context

<img width="996" alt="Bildschirmfoto 2023-11-22 um 12 32 13" src="https://github.com/nuxt/nuxt/assets/30939926/3f16630e-8519-4cbd-89ba-fadd18d1d3d4">

**Comment by awacode21** [comment]
The following is displayed on console:

[Vue warn]: Failed to resolve component: NuxtExampleLayout
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Non-function value encountered for default slot. Prefer function slots for better performance.
[Vue warn]: Component <Anonymous> is missing template or render function.

**Comment by arashsheyda** [comment]
This has been fixed by #63. thanks
